name: kpmg
services:
  github:
    image: github:latest
    ports:
      - "2222:22"
    volumes:
      - github:/home/git
    networks:
      - workshop
volumes:
  github:
    external: true
networks:
  workshop:
    external: true
