#! /bin/bash

configured=1
if [[ ! -d '/config/cn=config' ]]
then
    cp -a /etc/ldap/slapd.d/. /config/
    configured=0
fi
/usr/sbin/slapd -F /config  -u openldap -g openldap -h 'ldapi:// ldap://ldap:389'
if [[ ${configured} == 0 ]]
then
    sleep 5
    ldapmodify -Y EXTERNAL -H ldapi:/// -f /opt/ldap/setup.ldif
    ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/ldap/schema/msuser.ldif
    ldapadd -Y EXTERNAL -H ldapi:/// -f /opt/ldap/groups.ldif
    ldapadd -Y EXTERNAL -H ldapi:/// -f /opt/ldap/users.ldif
fi
tail -f /dev/null
